name: install dependencies
description: set up node & install dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'
        scope: '@jpyc'
    - name: Install dependencies
      run: yarn --frozen-lockfile
