name: publish package
description: publish an npm package
inputs:
  node-auth-token:
    description: 'node token for authorization'
    required: true

runs:
  using: composite
  steps:
    - name: Publish package
      run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ inputs.node-auth-token }}
