name: static checks

on:
  pull_request:
    branches:
      - main
      - develop
    types: [opened, synchronize, reopened, closed]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      pull-requests: read
    outputs:
      root: ${{ steps.filter.outputs.root }}
      core: ${{ steps.filter.outputs.core }}
      v1: ${{ steps.filter.outputs.v1 }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            root:
              - '.github/**'
              - 'docs/**'
              - 'README.md'
            core:
              - 'packages/core/**'
            v1:
              - 'packages/v1/**'

  check-root:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.root == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-dependencies
      - name: Format
        run: yarn run format:dry-run .github docs README.md

  check-core:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.core == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/core
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-dependencies
      - name: Compile
        run: yarn run compile
      - name: Lint
        run: yarn run lint:dry-run
      - name: Format
        run: yarn run format:dry-run
      - name: Run tests
        run: yarn run test

  check-v1:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.v1 == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/v1
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-dependencies
      - name: Compile
        run: yarn run compile
      - name: Lint
        run: yarn run lint:dry-run
      - name: Format
        run: yarn run format:dry-run
